<?php

use Illuminate\Database\Seeder;

class evaluacion_materiasescoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('evaluacion_materiasesco')->insert([
            
['id'=>1,'semestre'=>101,'clave'=>'AE','materia'=>'LIDERAZGO'],
['id'=>2,'semestre'=>101,'clave'=>'AE','materia'=>'INFORMATICA I'],
['id'=>3,'semestre'=>101,'clave'=>'AE','materia'=>'MATEMATICAS BASICAS'],
['id'=>4,'semestre'=>101,'clave'=>'AE','materia'=>'INTRODUCCION  A LA ADMINISTRACION'],
['id'=>5,'semestre'=>101,'clave'=>'AE','materia'=>'CONTABILIDAD I'],
['id'=>6,'semestre'=>101,'clave'=>'AE','materia'=>'AUTOCONOCIMIENTO Y DESARROLLO HUMANO'],
['id'=>7,'semestre'=>101,'clave'=>'AE','materia'=>'REDACCION Y ARGUMENTACION'],
['id'=>8,'semestre'=>101,'clave'=>'AR','materia'=>'DISEÑO ARQUITECTONICO I: INICIACION A LA COMPOSICION Y EXPRESION FORMAL'],
['id'=>9,'semestre'=>101,'clave'=>'AR','materia'=>'ETICA Y BIOETICA'],
['id'=>10,'semestre'=>101,'clave'=>'AR','materia'=>'FUNDAMENTOS DE FISICA, MATEMATICAS Y GEOMETRIA'],
['id'=>11,'semestre'=>101,'clave'=>'AR','materia'=>'DESARROLLO DE SABERES COGNOSCITIVOS'],
['id'=>12,'semestre'=>101,'clave'=>'AR','materia'=>'INTRODUCCION A LAS TEORIAS DE LA COMUNICACION E ICONICIDAD'],
['id'=>13,'semestre'=>101,'clave'=>'AR','materia'=>'METODOLOGIAS DE LA INVESTIGACION'],
['id'=>14,'semestre'=>101,'clave'=>'CT','materia'=>'AUTOCONOCIMIENTO Y DESARROLLO HUMANO'],
['id'=>15,'semestre'=>101,'clave'=>'CT','materia'=>'REDACCION'],
['id'=>16,'semestre'=>101,'clave'=>'CT','materia'=>'CAMPO Y OBJETO DE LA COMUNICACION'],
['id'=>17,'semestre'=>101,'clave'=>'CT','materia'=>'FORMACION PARA EL TRABAJO ACADEMICO'],
['id'=>18,'semestre'=>101,'clave'=>'CT','materia'=>'ESTUDIO DE LA ORGANIZACIONES'],
['id'=>19,'semestre'=>101,'clave'=>'CT','materia'=>'INDUSTRIAS MEDIATICAS'],
['id'=>20,'semestre'=>101,'clave'=>'CT','materia'=>'CONVERGENCIA MEDIATICA'],
['id'=>21,'semestre'=>101,'clave'=>'CF','materia'=>'INTRODUCCION A LA ADMINISTRACION'],
['id'=>22,'semestre'=>101,'clave'=>'CF','materia'=>'TECNOLOGIA DE LA INFORMACION Y COMUNICACION'],
['id'=>23,'semestre'=>101,'clave'=>'CF','materia'=>'LENGUA EXTRANJERA I'],
['id'=>24,'semestre'=>101,'clave'=>'CF','materia'=>'MATEMATICAS BASICAS'],
['id'=>25,'semestre'=>101,'clave'=>'CF','materia'=>'INTRODUCCION AL DERECHO'],
['id'=>26,'semestre'=>101,'clave'=>'CF','materia'=>'FUNDAMENTOS DE CONTABILIDAD'],
['id'=>27,'semestre'=>101,'clave'=>'CF','materia'=>'ECONOMIA Y GLOBALIZACION'],
['id'=>28,'semestre'=>101,'clave'=>'CF','materia'=>'COMUNICACION ORAL Y ESCRITA'],
['id'=>29,'semestre'=>101,'clave'=>'DE','materia'=>'TEORIA ECONOMICA'],
['id'=>30,'semestre'=>101,'clave'=>'DE','materia'=>'HISTORIA DEL DERECHO EN MEXICO'],
['id'=>31,'semestre'=>101,'clave'=>'DE','materia'=>'INTRODUCCION A LA CIENCIA JURIDICA I'],
['id'=>32,'semestre'=>101,'clave'=>'DE','materia'=>'TEORIA DEL ESTADO'],
['id'=>33,'semestre'=>101,'clave'=>'DE','materia'=>'SISTEMAS JURIDICOS COMPARADOS'],
['id'=>34,'semestre'=>101,'clave'=>'DE','materia'=>'ADMINISTRACION APLICADA AL DERECHO'],
['id'=>35,'semestre'=>101,'clave'=>'DE','materia'=>'DERECHO ROMANO I'],
['id'=>36,'semestre'=>101,'clave'=>'ID','materia'=>'ALGEBRA'],
['id'=>37,'semestre'=>101,'clave'=>'ID','materia'=>'INTRODUCCION A LA INGENIERIA INDUSTRIAL'],
['id'=>38,'semestre'=>101,'clave'=>'ID','materia'=>'INTRODUCCION TECNOLOGICAS DE LA INFORMACION'],
['id'=>39,'semestre'=>101,'clave'=>'ID','materia'=>'FISICA'],
['id'=>40,'semestre'=>101,'clave'=>'ID','materia'=>'LOGICA Y ARGUMENTACION'],
['id'=>41,'semestre'=>101,'clave'=>'ID','materia'=>'COMUNICACION ORAL Y ESCRITA'],
['id'=>42,'semestre'=>101,'clave'=>'ID','materia'=>'GEOMETRIA ANALITICA'],
['id'=>43,'semestre'=>101,'clave'=>'IM','materia'=>'FISICA'],
['id'=>44,'semestre'=>101,'clave'=>'IM','materia'=>'TALLER'],
['id'=>45,'semestre'=>101,'clave'=>'IM','materia'=>'ALGEBRA LINEAL'],
['id'=>46,'semestre'=>101,'clave'=>'IM','materia'=>'GESTION ELECTRONICA DE LA INFORMACION'],
['id'=>47,'semestre'=>101,'clave'=>'IM','materia'=>'ALGEBRA'],
['id'=>48,'semestre'=>101,'clave'=>'IM','materia'=>'REDACCION'],
['id'=>49,'semestre'=>101,'clave'=>'IM','materia'=>'LOGICA Y ARGUMENTACION'],
['id'=>50,'semestre'=>101,'clave'=>'IM','materia'=>'TEORIA DE CIRCUITOS I'],
['id'=>51,'semestre'=>101,'clave'=>'LM','materia'=>'LOGICA Y ARGUMENTACION'],
['id'=>52,'semestre'=>101,'clave'=>'LM','materia'=>'METODOS CUANTITATIVOS I'],
['id'=>53,'semestre'=>101,'clave'=>'LM','materia'=>'DERECHO DE PERSONAS Y DE LAS OBLIGACIONES'],
['id'=>54,'semestre'=>101,'clave'=>'LM','materia'=>'ADMINISTRACION'],
['id'=>55,'semestre'=>101,'clave'=>'LM','materia'=>'GESTION ELECTRONICA DE LA INFORMACION'],
['id'=>56,'semestre'=>101,'clave'=>'LM','materia'=>'INTRODUCCION A LA ECONOMIA'],
['id'=>57,'semestre'=>101,'clave'=>'LM','materia'=>'CONTABILIDAD FINANCIERA I'],
['id'=>58,'semestre'=>101,'clave'=>'IN','materia'=>'MATEMATICAS BASICAS'],
['id'=>59,'semestre'=>101,'clave'=>'IN','materia'=>'TECNOLOGIA INFORMATICA'],
['id'=>60,'semestre'=>101,'clave'=>'IN','materia'=>'INTRODUCCION A LA ADMINISTRACION'],
['id'=>61,'semestre'=>101,'clave'=>'IN','materia'=>'FUNDAMENTOS DE CONTABILIDAD'],
['id'=>62,'semestre'=>101,'clave'=>'IN','materia'=>'INTRODUCCION AL DERECHO'],
['id'=>63,'semestre'=>101,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA I (INGLES)'],
['id'=>64,'semestre'=>101,'clave'=>'IN','materia'=>'ESTRATEGIAS PARA EL ESTUDIO Y LA COMUNICACIÓN'],
['id'=>65,'semestre'=>101,'clave'=>'PS','materia'=>'TEORIA DEL CONOCIMIENTO'],
['id'=>66,'semestre'=>101,'clave'=>'PS','materia'=>'TALLER DE LECTURA Y REDACCION'],
['id'=>67,'semestre'=>101,'clave'=>'PS','materia'=>'INTRODUCCION A LA PSICOLOGIA'],
['id'=>68,'semestre'=>101,'clave'=>'PS','materia'=>'BASES BIOLOGICAS DE LA CONDUCTA'],
['id'=>69,'semestre'=>101,'clave'=>'PS','materia'=>'ESTADISTICA DESCRIPTIVA'],
['id'=>70,'semestre'=>101,'clave'=>'PS','materia'=>'LOGICA Y ARGUMENTACION'],
['id'=>71,'semestre'=>101,'clave'=>'PS','materia'=>'GESTION ELECTRONICA DE LA INFORMACION'],
['id'=>72,'semestre'=>102,'clave'=>'CT','materia'=>'AUTOCONOCIMIENTO Y DESARROLLO HUMANO'],
['id'=>73,'semestre'=>102,'clave'=>'CT','materia'=>'REDACCION'],
['id'=>74,'semestre'=>102,'clave'=>'CT','materia'=>'CAMPO Y OBJETO DE LA COMUNICACION'],
['id'=>75,'semestre'=>102,'clave'=>'CT','materia'=>'CONVERGENCIA MEDIATICA'],
['id'=>76,'semestre'=>102,'clave'=>'CT','materia'=>'FORMACION PARA EL TRABAJO ACADEMICO'],
['id'=>77,'semestre'=>102,'clave'=>'CT','materia'=>'ESTUDIO DE LAS ORGANIZACIONES'],
['id'=>78,'semestre'=>102,'clave'=>'CT','materia'=>'INDUSTRIAS MEDIATICAS'],
['id'=>79,'semestre'=>102,'clave'=>'DE','materia'=>'TEORIA ECONOMICA'],
['id'=>80,'semestre'=>102,'clave'=>'DE','materia'=>'SISTEMAS JURIDICOS COMPARADOS'],
['id'=>81,'semestre'=>102,'clave'=>'DE','materia'=>'HISTORIA DEL DERECHO EN MEXICO'],
['id'=>82,'semestre'=>102,'clave'=>'DE','materia'=>'INTRODUCCION A LA CIENCIA JURIDICA I'],
['id'=>83,'semestre'=>102,'clave'=>'DE','materia'=>'TEORIA DEL ESTADO'],
['id'=>84,'semestre'=>102,'clave'=>'DE','materia'=>'DERECHO ROMANO I'],
['id'=>85,'semestre'=>102,'clave'=>'DE','materia'=>'ADMINISTRACION APLICADA AL DERECHO'],
['id'=>86,'semestre'=>102,'clave'=>'IN','materia'=>'INTRODUCCION AL DERECHO'],
['id'=>87,'semestre'=>102,'clave'=>'IN','materia'=>'INTRODUCCION A LA ADMINISTRACION'],
['id'=>88,'semestre'=>102,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA I'],
['id'=>89,'semestre'=>102,'clave'=>'IN','materia'=>'TECNOLOGIA INFORMATICA'],
['id'=>90,'semestre'=>102,'clave'=>'IN','materia'=>'ESTRATEGIAS PARA EL ESTUDIO Y LA COMUNICACION'],
['id'=>91,'semestre'=>102,'clave'=>'IN','materia'=>'MATEMATICAS BASICAS'],
['id'=>92,'semestre'=>102,'clave'=>'IN','materia'=>'FUNDAMENTOS DE CONTABILIDAD'],
['id'=>93,'semestre'=>301,'clave'=>'AE','materia'=>'ANALISIS Y DISEÑO DE ORGANIZACIONES'],
['id'=>94,'semestre'=>301,'clave'=>'AE','materia'=>'SOCIOLOGIA DE LA EMPRESA'],
['id'=>95,'semestre'=>301,'clave'=>'AE','materia'=>'ECONOMIA II'],
['id'=>96,'semestre'=>301,'clave'=>'AE','materia'=>'ESTADISTICA'],
['id'=>97,'semestre'=>301,'clave'=>'AE','materia'=>'CONTABILIDAD DE COSTOS'],
['id'=>98,'semestre'=>301,'clave'=>'AE','materia'=>'EMPRENDEDORES II'],
['id'=>99,'semestre'=>301,'clave'=>'AE','materia'=>'DERECHO MERCANTIL'],
['id'=>100,'semestre'=>301,'clave'=>'CT','materia'=>'INVESTIGACION CUALITATIVA I'],
['id'=>101,'semestre'=>301,'clave'=>'CT','materia'=>'PREPRENSA DIGITAL'],
['id'=>102,'semestre'=>301,'clave'=>'CT','materia'=>'ESTRUCTURALISMO: SENTIDOS DEL MENSAJE'],
['id'=>103,'semestre'=>301,'clave'=>'CT','materia'=>'COMUNICACION VISUAL: CARTEL Y COMIC'],
['id'=>104,'semestre'=>301,'clave'=>'CT','materia'=>'MULTIMEDIA'],
['id'=>105,'semestre'=>301,'clave'=>'CT','materia'=>'PERIODISMO II'],
['id'=>106,'semestre'=>301,'clave'=>'CT','materia'=>'CORPORATIVO: IDENTIDAD E IMAGEN'],
['id'=>107,'semestre'=>301,'clave'=>'CT','materia'=>'TECNOLOGIA E INFORMACION'],
['id'=>108,'semestre'=>301,'clave'=>'CT','materia'=>'FOTOGRAFIA II: TEMAS Y TECNICAS'],
['id'=>109,'semestre'=>301,'clave'=>'DE','materia'=>'GARANTIAS CONSTITUCIONALES'],
['id'=>110,'semestre'=>301,'clave'=>'DE','materia'=>'PROBLEMAS JURIDICOS CONTEMPORANEOS'],
['id'=>111,'semestre'=>301,'clave'=>'DE','materia'=>'DERECHO MERCANTIL'],
['id'=>112,'semestre'=>301,'clave'=>'DE','materia'=>'CRIMINOLOGIA Y POLITICA CRIMINAL'],
['id'=>113,'semestre'=>301,'clave'=>'DE','materia'=>'REDACCION JURIDICA Y ORATORIA'],
['id'=>114,'semestre'=>301,'clave'=>'DE','materia'=>'SOCIOLOGIA Y REALISMO JURIDICO'],
['id'=>115,'semestre'=>301,'clave'=>'DE','materia'=>'DERECHO CIVIL I'],
['id'=>116,'semestre'=>301,'clave'=>'DE','materia'=>'DERECHOS HUMANOS Y ORGANOS DE PROTECCION INTERNACIONAL'],
['id'=>117,'semestre'=>301,'clave'=>'IM','materia'=>'ELECTRONICA II'],
['id'=>118,'semestre'=>301,'clave'=>'IM','materia'=>'METODOS DE INVESTIGACION II'],
['id'=>119,'semestre'=>301,'clave'=>'IM','materia'=>'TEORIA DE  CIRCUITOS II'],
['id'=>120,'semestre'=>301,'clave'=>'IM','materia'=>'ESTRUCTURAS DE DATOS Y ALGORITMOS'],
['id'=>121,'semestre'=>301,'clave'=>'IM','materia'=>'ECUACIONES DIFERENCIALES'],
['id'=>122,'semestre'=>301,'clave'=>'IM','materia'=>'COMUNICACION Y RELACIONES HUMANAS'],
['id'=>123,'semestre'=>301,'clave'=>'IM','materia'=>'MECANICA II'],
['id'=>124,'semestre'=>301,'clave'=>'LM','materia'=>'METODOS DE INVESTIGACION II'],
['id'=>125,'semestre'=>301,'clave'=>'LM','materia'=>'INVESTIGACION DE MERCADOS I'],
['id'=>126,'semestre'=>301,'clave'=>'LM','materia'=>'MACROECONOMIA'],
['id'=>127,'semestre'=>301,'clave'=>'LM','materia'=>'ESTADISTICA'],
['id'=>128,'semestre'=>301,'clave'=>'LM','materia'=>'CONTABILIDAD DE COSTOS'],
['id'=>129,'semestre'=>301,'clave'=>'LM','materia'=>'COMUNICACION Y RELACIONES HUMANAS'],
['id'=>130,'semestre'=>301,'clave'=>'LM','materia'=>'COMPORTAMIENTO DEL CONSUMIDOR'],
['id'=>131,'semestre'=>301,'clave'=>'IN','materia'=>'MICROECONOMIA'],
['id'=>132,'semestre'=>301,'clave'=>'IN','materia'=>'MERCADOTECNIA INTERNACIONAL I'],
['id'=>133,'semestre'=>301,'clave'=>'IN','materia'=>'MULTICULTURALIDAD, IDENTIDAD Y GLOBALIZACION'],
['id'=>134,'semestre'=>301,'clave'=>'IN','materia'=>'ESTRATEGIAS Y TECNICAS DE NEGOCIACION'],
['id'=>135,'semestre'=>301,'clave'=>'IN','materia'=>'ESTRUCTURA Y TEORIA DEL COMERCIO INTERNACIONAL'],
['id'=>136,'semestre'=>301,'clave'=>'IN','materia'=>'METODOS DE INVESTIGACION I'],
['id'=>137,'semestre'=>301,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA III'],
['id'=>138,'semestre'=>301,'clave'=>'IN','materia'=>'CONTABILIDAD DE COSTOS'],
['id'=>139,'semestre'=>301,'clave'=>'IN','materia'=>'NORMAS JURIDICAS Y FISCALES DEL COMERCIO EXTERIOR'],
['id'=>140,'semestre'=>301,'clave'=>'PS','materia'=>'PSICOTRASTORNOS EN LA INFANCIA Y ADOLESCENCIA'],
['id'=>141,'semestre'=>301,'clave'=>'PS','materia'=>'PSICOLOGIA COMUNITARIA'],
['id'=>142,'semestre'=>301,'clave'=>'PS','materia'=>'MULTICULTURALISMO'],
['id'=>143,'semestre'=>301,'clave'=>'PS','materia'=>'TEORIA Y TECNICA DE LA ENTREVISTA I'],
['id'=>144,'semestre'=>301,'clave'=>'PS','materia'=>'INTRODUCCION A LA INVESTIGACION'],
['id'=>145,'semestre'=>301,'clave'=>'PS','materia'=>'DESARROLLO DE LA ADULTEZ A LA VEJEZ'],
['id'=>146,'semestre'=>301,'clave'=>'PS','materia'=>'TEORIAS DE LA PERSONALIDAD'],
['id'=>147,'semestre'=>302,'clave'=>'DE','materia'=>'PROBLEMAS JURIDICOS CONTEMPORANEOS'],
['id'=>148,'semestre'=>302,'clave'=>'DE','materia'=>'DERECHO CIVIL I'],
['id'=>149,'semestre'=>302,'clave'=>'DE','materia'=>'DERECHO MERCANTIL'],
['id'=>150,'semestre'=>302,'clave'=>'DE','materia'=>'REDACCION JURIDICA Y ORATORIA'],
['id'=>151,'semestre'=>302,'clave'=>'CX','materia'=>'INGLES'],
['id'=>152,'semestre'=>302,'clave'=>'DE','materia'=>'DERECHOS HUMANOS Y ORGANOS DE PROTECCION INTERNACIONAL'],
['id'=>153,'semestre'=>302,'clave'=>'DE','materia'=>'GARANTIAS CONSTITUCIONALES'],
['id'=>154,'semestre'=>302,'clave'=>'DE','materia'=>'CRIMINOLOGIA Y POLITICA CRIMINAL'],
['id'=>155,'semestre'=>302,'clave'=>'DE','materia'=>'SOCIOLOGIA Y REALISMO JURIDICO'],
['id'=>156,'semestre'=>302,'clave'=>'IN','materia'=>'MULTICULTURALIDAD, IDENTIDAD Y GLOBALIZACION'],
['id'=>157,'semestre'=>302,'clave'=>'IN','materia'=>'MERCADOTECNIA INTERNACIONAL I'],
['id'=>158,'semestre'=>302,'clave'=>'IN','materia'=>'ESTRUCTURA Y TEORIA DEL COMERCIO INTERNACIONAL'],
['id'=>159,'semestre'=>302,'clave'=>'IN','materia'=>'ESTRATEGIAS Y TECNICAS DE NEGOCIACION'],
['id'=>160,'semestre'=>302,'clave'=>'IN','materia'=>'MICROECONOMIA'],
['id'=>161,'semestre'=>302,'clave'=>'IN','materia'=>'METODOS DE INVESTIGACION I'],
['id'=>162,'semestre'=>302,'clave'=>'IN','materia'=>'CONTABILIDAD DE COSTOS'],
['id'=>163,'semestre'=>302,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA III'],
['id'=>164,'semestre'=>302,'clave'=>'IN','materia'=>'NORMAS JURIDICAS Y FISCALES DEL COMERCIO EXTERIOR'],
['id'=>165,'semestre'=>501,'clave'=>'AE','materia'=>'DESARROLLO ORGANIZACIONAL'],
['id'=>166,'semestre'=>501,'clave'=>'AE','materia'=>'RECURSOS HUMANOS II'],
['id'=>167,'semestre'=>501,'clave'=>'AE','materia'=>'PLANEACION FISCAL'],
['id'=>168,'semestre'=>501,'clave'=>'AE','materia'=>'DISEÑO DE INVESTIGACION'],
['id'=>169,'semestre'=>501,'clave'=>'AE','materia'=>'PLANEACION FINANCIERA'],
['id'=>170,'semestre'=>501,'clave'=>'AE','materia'=>'INVESTIGACION DE MERCADOS'],
['id'=>171,'semestre'=>501,'clave'=>'AE','materia'=>'PRESUPUESTOS'],
['id'=>172,'semestre'=>501,'clave'=>'CT','materia'=>'SOCIEDAD Y ECONOMIA'],
['id'=>173,'semestre'=>501,'clave'=>'CT','materia'=>'INVESTIGACION POR ENCUESTA'],
['id'=>174,'semestre'=>501,'clave'=>'CT','materia'=>'CINE II'],
['id'=>175,'semestre'=>501,'clave'=>'CT','materia'=>'OPINION PUBLICA'],
['id'=>176,'semestre'=>501,'clave'=>'CT','materia'=>'RADIO II'],
['id'=>177,'semestre'=>501,'clave'=>'CT','materia'=>'MERCADOTECNIA ESTRATEGICA'],
['id'=>178,'semestre'=>501,'clave'=>'CT','materia'=>'COMPOSICON DIGITAL'],
['id'=>179,'semestre'=>501,'clave'=>'CT','materia'=>'COMUNICACION EDUCATIVA'],
['id'=>180,'semestre'=>501,'clave'=>'DE','materia'=>'DERECHO AGRARIO'],
['id'=>181,'semestre'=>501,'clave'=>'DE','materia'=>'DERECHO ADMINISTRATIVO'],
['id'=>182,'semestre'=>501,'clave'=>'DE','materia'=>'SISTEMAS DE CONTROL CONSTITUCIONAL'],
['id'=>183,'semestre'=>501,'clave'=>'DE','materia'=>'TECNICA LEGISLATIVA Y JURISPRUDENCIAL'],
['id'=>184,'semestre'=>501,'clave'=>'DE','materia'=>'DERECHO PROCESAL MERCANTIL'],
['id'=>185,'semestre'=>501,'clave'=>'DE','materia'=>'DERECHO INTERNACIONAL PRIVADO'],
['id'=>186,'semestre'=>501,'clave'=>'DE','materia'=>'DERECHO PROCESAL CIVIL'],
['id'=>187,'semestre'=>501,'clave'=>'DE','materia'=>'DERECHO PENAL II'],
['id'=>188,'semestre'=>501,'clave'=>'IM','materia'=>'ARQUITECTURA DE COMPUTADORAS'],
['id'=>189,'semestre'=>501,'clave'=>'IM','materia'=>'MECANICA DE FLUIDOS'],
['id'=>190,'semestre'=>501,'clave'=>'IM','materia'=>'TRANSMISION DE DATOS'],
['id'=>191,'semestre'=>501,'clave'=>'IM','materia'=>'CONTABILIDAD'],
['id'=>192,'semestre'=>501,'clave'=>'IM','materia'=>'PROGRAMACION ORIENTADA A OBJETOS'],
['id'=>193,'semestre'=>501,'clave'=>'IM','materia'=>'TEORIA DE CONTROL II'],
['id'=>194,'semestre'=>501,'clave'=>'IM','materia'=>'TERMODINAMICA'],
['id'=>195,'semestre'=>501,'clave'=>'LM','materia'=>'DISEÑO GRAFICO'],
['id'=>196,'semestre'=>501,'clave'=>'LM','materia'=>'GESTION ESTRATEGICA DE LA DISTRIBUCION'],
['id'=>197,'semestre'=>501,'clave'=>'LM','materia'=>'FIJACION DE PRECIOS'],
['id'=>198,'semestre'=>501,'clave'=>'LM','materia'=>'GESTION ESTRATEGICA DE VENTAS'],
['id'=>199,'semestre'=>501,'clave'=>'LM','materia'=>'PUBLICIDAD II'],
['id'=>200,'semestre'=>501,'clave'=>'LM','materia'=>'ADMINISTRACION FINANCIERA'],
['id'=>201,'semestre'=>501,'clave'=>'LM','materia'=>'RELACIONES PUBLICAS II'],
['id'=>202,'semestre'=>501,'clave'=>'IN','materia'=>'POLITICA ECONOMICA EXTERIOR'],
['id'=>203,'semestre'=>501,'clave'=>'IN','materia'=>'SISTEMAS GERENCIALES'],
['id'=>204,'semestre'=>501,'clave'=>'IN','materia'=>'LEGISLACION ADUANERA'],
['id'=>205,'semestre'=>501,'clave'=>'IN','materia'=>'FINANCIAMIENTO INTERNACIONAL'],
['id'=>206,'semestre'=>501,'clave'=>'IN','materia'=>'METODOS DE INVESTIGACION III'],
['id'=>207,'semestre'=>501,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA V'],
['id'=>208,'semestre'=>501,'clave'=>'IN','materia'=>'INVESTIGACION DE OPERACIONES'],
['id'=>209,'semestre'=>501,'clave'=>'IN','materia'=>'TRATADOS COMERCIALES CON NORTEAMERICA'],
['id'=>210,'semestre'=>501,'clave'=>'PS','materia'=>'EVALUACION PSICOLOGICA DE ADULTOS'],
['id'=>211,'semestre'=>501,'clave'=>'PS','materia'=>'METODOS Y TECNICAS DE INTERVENCION EN NIÑOS Y ADOLESCENTES'],
['id'=>212,'semestre'=>501,'clave'=>'PS','materia'=>'DIFICULTADES Y PROBLEMAS DE APRENDIZAJE I'],
['id'=>213,'semestre'=>501,'clave'=>'PS','materia'=>'METODOS DE INVESTIGACION CUALITATIVA'],
['id'=>214,'semestre'=>501,'clave'=>'PS','materia'=>'EVALUACION Y PLANEACION DE LA INTERVENCION PSICOSOCIAL'],
['id'=>215,'semestre'=>501,'clave'=>'PS','materia'=>'EVALUACION PSICOPEDAGOGICA I'],
['id'=>216,'semestre'=>501,'clave'=>'PS','materia'=>'SEXUALIDAD HUMANA'],
['id'=>217,'semestre'=>502,'clave'=>'CT','materia'=>'SOCIEDAD Y ECONOMIA'],
['id'=>218,'semestre'=>502,'clave'=>'CT','materia'=>'MERCADOTECNIA ESTRATEGICA'],
['id'=>219,'semestre'=>502,'clave'=>'CT','materia'=>'OPINION PUBLICA'],
['id'=>220,'semestre'=>502,'clave'=>'CT','materia'=>'COMUNICACION EDUCATIVA'],
['id'=>221,'semestre'=>502,'clave'=>'CT','materia'=>'INVESTIGACION POR ENCUESTA'],
['id'=>222,'semestre'=>502,'clave'=>'CT','materia'=>'CINE II'],
['id'=>223,'semestre'=>502,'clave'=>'CT','materia'=>'RADIO II'],
['id'=>224,'semestre'=>502,'clave'=>'CT','materia'=>'COMPOSICION DIGITAL'],
['id'=>225,'semestre'=>502,'clave'=>'DE','materia'=>'DERECHO INTERNACIONAL PRIVADO'],
['id'=>226,'semestre'=>502,'clave'=>'DE','materia'=>'DERECHO AGRARIO'],
['id'=>227,'semestre'=>502,'clave'=>'DE','materia'=>'DERECHO PROCESAL CIVIL'],
['id'=>228,'semestre'=>502,'clave'=>'DE','materia'=>'DERECHO ADMINISTRATIVO'],
['id'=>229,'semestre'=>502,'clave'=>'DE','materia'=>'SISTEMAS DE CONTROL CONSTITUCIONAL'],
['id'=>230,'semestre'=>502,'clave'=>'DE','materia'=>'TECNICA LEGISLATIVA Y JURISPRUDENCIAL'],
['id'=>231,'semestre'=>502,'clave'=>'DE','materia'=>'DERECHO PROCESAL MERCANTIL'],
['id'=>232,'semestre'=>502,'clave'=>'DE','materia'=>'DERECHO PENAL II'],
['id'=>233,'semestre'=>701,'clave'=>'AE','materia'=>'SEMINARIO DE DESARROLLO EMPRESARIAL'],
['id'=>234,'semestre'=>701,'clave'=>'AE','materia'=>'DESARROLLO DE HABILIDADES DIRECTIVAS'],
['id'=>235,'semestre'=>701,'clave'=>'AE','materia'=>'ADMINISTRACION DE LA PRODUCCION II'],
['id'=>236,'semestre'=>701,'clave'=>'AE','materia'=>'IMPUESTOS II'],
['id'=>237,'semestre'=>701,'clave'=>'AE','materia'=>'SEMINARIO DE TESIS I'],
['id'=>238,'semestre'=>701,'clave'=>'AE','materia'=>'ESTRATEGIAS DE PROMOCION'],
['id'=>239,'semestre'=>701,'clave'=>'AE','materia'=>'FINANZAS'],
['id'=>240,'semestre'=>701,'clave'=>'CT','materia'=>'SEMINARIO DE TESIS I'],
['id'=>241,'semestre'=>701,'clave'=>'CT','materia'=>'TALLER DE DEBATE'],
['id'=>242,'semestre'=>701,'clave'=>'CT','materia'=>'MODELAJE TERCERA DIMENSION'],
['id'=>243,'semestre'=>701,'clave'=>'CT','materia'=>'PENSAMIENTO POLITICO CONTEMPORANEO'],
['id'=>244,'semestre'=>701,'clave'=>'CT','materia'=>'SEMINARIO DE TESIS I'],
['id'=>245,'semestre'=>701,'clave'=>'CT','materia'=>'PRODUCCION TELEVISIVA'],
['id'=>246,'semestre'=>701,'clave'=>'CT','materia'=>'CAMPAÑAS PUBLICITARIAS'],
['id'=>247,'semestre'=>701,'clave'=>'DE','materia'=>'TALLER DE SOLUCION DE CASOS PRACTICOS'],
['id'=>248,'semestre'=>701,'clave'=>'DE','materia'=>'REGIMEN LEGAL DEL COMERCIO EXTERIOR'],
['id'=>249,'semestre'=>701,'clave'=>'DE','materia'=>'DERECHO FISCAL II'],
['id'=>250,'semestre'=>701,'clave'=>'DE','materia'=>'DERECHO LABORAL II'],
['id'=>251,'semestre'=>701,'clave'=>'DE','materia'=>'SEMINARIO DE TITULACION I'],
['id'=>252,'semestre'=>701,'clave'=>'DE','materia'=>'DERECHO INFORMATICO'],
['id'=>253,'semestre'=>701,'clave'=>'DE','materia'=>'CONCURSOS E INSTITUCIONES AUXILIARES DE CREDITO'],
['id'=>254,'semestre'=>701,'clave'=>'DE','materia'=>'AMPARO I'],
['id'=>255,'semestre'=>701,'clave'=>'IM','materia'=>'REDES DE COMUNICACION'],
['id'=>256,'semestre'=>701,'clave'=>'IM','materia'=>'ECONOMIA'],
['id'=>257,'semestre'=>701,'clave'=>'IM','materia'=>'SEMINARIO DE TESIS I'],
['id'=>258,'semestre'=>701,'clave'=>'IM','materia'=>'INFORMACION VISUAL'],
['id'=>259,'semestre'=>701,'clave'=>'IM','materia'=>'ROBOTICA'],
['id'=>260,'semestre'=>701,'clave'=>'IM','materia'=>'FINANZAS'],
['id'=>261,'semestre'=>701,'clave'=>'LM','materia'=>'SEMINARIO DE TESIS I'],
['id'=>262,'semestre'=>701,'clave'=>'LM','materia'=>'MERCADOTECNIA INDUSTRIAL'],
['id'=>263,'semestre'=>701,'clave'=>'LM','materia'=>'MERCADOTECNIA DE NEGOCIOS TURISTICOS'],
['id'=>264,'semestre'=>701,'clave'=>'LM','materia'=>'MERCADOTECNIA INSTITUCIONAL'],
['id'=>265,'semestre'=>701,'clave'=>'LM','materia'=>'PROMOCION DE VENTAS'],
['id'=>266,'semestre'=>701,'clave'=>'LM','materia'=>'EVALUACION DE MEDIOS'],
['id'=>267,'semestre'=>701,'clave'=>'LM','materia'=>'IMAGEN CORPORATIVA'],
['id'=>268,'semestre'=>701,'clave'=>'IN','materia'=>'SEMINARIO DE TITULACION I'],
['id'=>269,'semestre'=>701,'clave'=>'IN','materia'=>'TRATADOS COMERCIALES CON ASIA-PACIFICO'],
['id'=>270,'semestre'=>701,'clave'=>'IN','materia'=>'COMERCIO ELECTRONICO Y ALTERNATIVO'],
['id'=>271,'semestre'=>701,'clave'=>'IN','materia'=>'ADMINISTRACION FINANCIERA'],
['id'=>272,'semestre'=>701,'clave'=>'IN','materia'=>'SISTEMAS DE CALIDAD'],
['id'=>273,'semestre'=>701,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA II (FRANCES)'],
['id'=>274,'semestre'=>701,'clave'=>'IN','materia'=>'CONTRATOS INTERNACIONALES'],
['id'=>275,'semestre'=>701,'clave'=>'IN','materia'=>'LENGUA EXTRANJERA APLICADA A LOS NEGOCIOS I'],
['id'=>276,'semestre'=>701,'clave'=>'PS','materia'=>'METODOS Y TECNICAS DE INTERVENCION EN GRUPOS'],
['id'=>277,'semestre'=>701,'clave'=>'PS','materia'=>'PSICOLOGIA Y COEDUCACION'],
['id'=>278,'semestre'=>701,'clave'=>'PS','materia'=>'AUTOCONOCIMIENTO PARA EL EJERCICIO DE LA PSICOLOGIA'],
['id'=>279,'semestre'=>701,'clave'=>'PS','materia'=>'AMBITOS DE APLICACION EN PSICOLOGIA DE LA SALUD EN MEXICO'],
['id'=>280,'semestre'=>701,'clave'=>'PS','materia'=>'INTERVENCION SOCIAL EN LA COMUNIDAD'],
['id'=>281,'semestre'=>701,'clave'=>'PS','materia'=>'SEMINARIO DE TESIS I'],
['id'=>282,'semestre'=>101,'clave'=>'CX','materia'=>'INGLES (ADMINISTRACION DE EMPRESAS)'],
['id'=>283,'semestre'=>101,'clave'=>'CX','materia'=>'INGLES (CIENCIAS Y TECNICAS DE LA COMUNICACIÓN)'],
['id'=>284,'semestre'=>101,'clave'=>'CX','materia'=>'INGLES (DERECHO)'],
['id'=>285,'semestre'=>101,'clave'=>'CX','materia'=>'INGLES (INGENIERIA EN MECATRONICA)'],
['id'=>286,'semestre'=>101,'clave'=>'CX','materia'=>'INGLES (PSICOLOGIA)'],
['id'=>287,'semestre'=>101,'clave'=>'CX','materia'=>'INGLES (MERCADOTECNIA)'],
['id'=>288,'semestre'=>102,'clave'=>'CX','materia'=>'INGLES (CIENCIAS Y TECNICAS DE LA COMUNICACIÓN)'],
['id'=>289,'semestre'=>102,'clave'=>'CX','materia'=>'INGLES (DERECHO)'],
['id'=>290,'semestre'=>301,'clave'=>'CX','materia'=>'INGLES (DERECHO)'],
['id'=>291,'semestre'=>301,'clave'=>'CX','materia'=>'INGLES (PSICOLOGIA)'],
['id'=>292,'semestre'=>301,'clave'=>'CX','materia'=>'INGLES (ADMINISTRACION DE EMPRESAS)'],
['id'=>293,'semestre'=>301,'clave'=>'CX','materia'=>'INGLES (CIENCIAS Y TECNICAS DE LA COMUNICACIÓN)'],
['id'=>294,'semestre'=>301,'clave'=>'CX','materia'=>'INGLES (INGENIERIA EN MECATRONICA)'],
['id'=>295,'semestre'=>301,'clave'=>'CX','materia'=>'INGLES (MERCADOTECNIA)'],
['id'=>296,'semestre'=>302,'clave'=>'CX','materia'=>'INGLES (DERECHO)']




        ]);
    }
}
