<?php

use Illuminate\Database\Seeder;

class evaluacion_maestrosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('evaluacion_maestros')->insert([
            ['id'=>1,'nombre'=>'CASTILLO MARTINEZ SAHAMALIA CRISTINA'],
            ['id'=>2,'nombre'=>'ESCOBAR GOMEZ DANIEL'],
            ['id'=>3,'nombre'=>'GARCIA DIAZ JUAN JOSE'],
            ['id'=>4,'nombre'=>'RAMIREZ AYALA GEORGINA MARIA'],
            ['id'=>5,'nombre'=>'SARUR ZANATTA MARIA SUSANA'],
            ['id'=>6,'nombre'=>'TOVAR SANCHEZ GABRIELA'],
            ['id'=>7,'nombre'=>'VERA GUERRA MARIO HUGO'],
            ['id'=>8,'nombre'=>'ALLEN AMESCUA JORGE ALBERTO'],
            ['id'=>9,'nombre'=>'AMANTE HADDAD SERGIO'],
            ['id'=>10,'nombre'=>'CORTEZ ZAHAR MIGUEL ANGEL'],
            ['id'=>11,'nombre'=>'FERNANDEZ LOMELIN MARIA TERESA'],
            ['id'=>12,'nombre'=>'D AVILA SIQUEIRA NETO GUSTAVO'],
            ['id'=>13,'nombre'=>'YEPEZ OLVERA LILIANA'],
            ['id'=>14,'nombre'=>'CHIPULI SANTIAGO MIGUEL ADOLFO JESUS'],
            ['id'=>15,'nombre'=>'DEL ANGEL VIDAL PABLO'],
            ['id'=>16,'nombre'=>'FERNANDEZ RIVERA ADAENA'],
            ['id'=>17,'nombre'=>'GONZALEZ ARROYO FERNANDO AXAYACATL'],
            ['id'=>18,'nombre'=>'GONZALEZ MUÑOZ VERONICA ALEJANDRA'],
            ['id'=>19,'nombre'=>'LOPEZ CASTILLO YOSUE SHALOM'],
            ['id'=>20,'nombre'=>'MEDRANO BARRENA JUAN CARLOS'],
            ['id'=>21,'nombre'=>'BARCLAY ARCE EDUARDO'],
            ['id'=>22,'nombre'=>'ESCOBAR GOMEZ DANIEL'],
            ['id'=>23,'nombre'=>'PORRAS ZARATE ANA LUISA'],
            ['id'=>24,'nombre'=>'RIOS GABRIEL ESLYSS'],
            ['id'=>25,'nombre'=>'ROMERO VALDES JOSE FRANCISCO'],
            ['id'=>26,'nombre'=>'SARUR ZANATTA MARIA SUSANA'],
            ['id'=>27,'nombre'=>'SUAREZ SANTOS LILIANA'],
            ['id'=>28,'nombre'=>'VERA GUERRA MARIO HUGO'],
            ['id'=>29,'nombre'=>'CARILLO CUEVAS PEDRO CARLOS'],
            ['id'=>30,'nombre'=>'DIAZ REBOLLEDO JOSE DE JESUS'],
            ['id'=>31,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>32,'nombre'=>'HERRERA BUSTAMANTE HECTOR'],
            ['id'=>33,'nombre'=>'AGUILERA DE HOMBRE FERNANDO'],
            ['id'=>34,'nombre'=>'RODRIGUEZ FERNANDEZ BENITO'],
            ['id'=>35,'nombre'=>'SANCHEZ VIGIL BERNARDO MIGUEL'],
            ['id'=>36,'nombre'=>'CARRILLO RAMON NORBERTO'],
            ['id'=>37,'nombre'=>'DIAZ ROMERO JOSE AGUSTIN'],
            ['id'=>38,'nombre'=>'RAMIREZ CASTRO RAFAEL'],
            ['id'=>39,'nombre'=>'ORTIZ GAMINO HECTOR'],
            ['id'=>40,'nombre'=>'SANCHEZ AGUILAR DIEGO'],
            ['id'=>41,'nombre'=>'SANCHEZ LARA GONZALO'],
            ['id'=>42,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>43,'nombre'=>'DURAN OLVERA JESSY MARLENE'],
            ['id'=>44,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>45,'nombre'=>'ORTIZ GAMINO HECTOR'],
            ['id'=>46,'nombre'=>'RAMIREZ CASTRO RAFAEL'],
            ['id'=>47,'nombre'=>'REYES SIERRA MARIA MARGARITA'],
            ['id'=>48,'nombre'=>'RODRIGUEZ LAGUNES NALDY PATRICIA'],
            ['id'=>49,'nombre'=>'SANCHEZ AGUILAR DIEGO'],
            ['id'=>50,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>51,'nombre'=>'CARMONA SANCHEZ HECTOR ORLANDO'],
            ['id'=>52,'nombre'=>'GARCIA DIAZ JUAN JOSE'],
            ['id'=>53,'nombre'=>'GARCIA LANDERO JULIO CESAR'],
            ['id'=>54,'nombre'=>'RAMIREZ AYALA GEORGINA MARIA'],
            ['id'=>55,'nombre'=>'RIOS GABRIEL ESLYSS'],
            ['id'=>56,'nombre'=>'SUAREZ SANTOS LILIANA'],
            ['id'=>57,'nombre'=>'VARGAS CASTRO EUGENIO MARIA'],
            ['id'=>58,'nombre'=>'GARCIA DIAZ JUAN JOSE'],
            ['id'=>59,'nombre'=>'GONZALEZ HERRERA JESUS ARTURO'],
            ['id'=>60,'nombre'=>'ORTIZ GARCIA JUAN MANUEL'],
            ['id'=>61,'nombre'=>'PEREA GONZALEZ ROSALIA'],
            ['id'=>62,'nombre'=>'POBLETE CRUZ UBALDO'],
            ['id'=>63,'nombre'=>'PORRAS ZARATE ANA LUISA'],
            ['id'=>64,'nombre'=>'TOVAR SANCHEZ GABRIELA'],
            ['id'=>65,'nombre'=>'CARMONA SANCHEZ HECTOR ORLANDO'],
            ['id'=>66,'nombre'=>'FERNANDEZ LOMELIN MARIA TERESA'],
            ['id'=>67,'nombre'=>'KAI CACHO VICTORIA'],
            ['id'=>68,'nombre'=>'PABELLO SOSA MARCELA'],
            ['id'=>69,'nombre'=>'REYES SIERRA MARIA MARGARITA'],
            ['id'=>70,'nombre'=>'SANCHEZ AGUILAR DIEGO'],
            ['id'=>71,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>72,'nombre'=>'CASTILLO MARTINEZ SAHAMALIA CRISTINA'],
            ['id'=>73,'nombre'=>'ELORZA VASQUEZ MIGUEL ANGEL'],
            ['id'=>74,'nombre'=>'FERNANDEZ RIVERA ADAENA'],
            ['id'=>75,'nombre'=>'GARCIA FLORES LEV'],
            ['id'=>76,'nombre'=>'GONZALEZ ARROYO FERNANDO AXAYACATL'],
            ['id'=>77,'nombre'=>'GONZALEZ MUÑOZ VERONICA ALEJANDRA'],
            ['id'=>78,'nombre'=>'LOPEZ CASTILLO YOSUE SHALOM'],
            ['id'=>79,'nombre'=>'BORJA CASTAÑEDA ESTHER'],
            ['id'=>80,'nombre'=>'CUEVAS PALACIOS ESTELA GUADALUPE'],
            ['id'=>81,'nombre'=>'DIAZ REBOLLEDO JOSE DE JESUS'],
            ['id'=>82,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>83,'nombre'=>'HERRERA BUSTAMANTE HECTOR'],
            ['id'=>84,'nombre'=>'SANCHEZ VIGIL BERNARDO MIGUEL'],
            ['id'=>85,'nombre'=>'VARGAS CASTRO EUGENIO MARIA'],
            ['id'=>86,'nombre'=>'GARCIA LANDERO JULIO CESAR'],
            ['id'=>87,'nombre'=>'GONZALEZ MUÑOZ VERONICA ALEJANDRA'],
            ['id'=>88,'nombre'=>'PEREZ LOPEZ JULIETA'],
            ['id'=>89,'nombre'=>'RIOS GABRIEL ESLYSS'],
            ['id'=>90,'nombre'=>'SANCHEZ LARA GONZALO'],
            ['id'=>91,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>92,'nombre'=>'SARUR ZANATTA MARIA SUSANA'],
            ['id'=>93,'nombre'=>'BARCLAY ARCE EDUARDO'],
            ['id'=>94,'nombre'=>'BATIZA SONI FERNANDO'],
            ['id'=>95,'nombre'=>'BORJA CASTAÑEDA ESTHER'],
            ['id'=>96,'nombre'=>'DIAZ ROMERO JOSE AGUSTIN'],
            ['id'=>97,'nombre'=>'HERNANDEZ VALENCIA GUADALUPE DEL CARMEN'],
            ['id'=>98,'nombre'=>'POBLETE CASTILLO EDUARDO FABRIZIO'],
            ['id'=>99,'nombre'=>'ROMERO VALDES JOSE FRANCISCO'],
            ['id'=>100,'nombre'=>'CONTRERAS SANCHEZ IRWING'],
            ['id'=>101,'nombre'=>'CORRALES AMEZCUA ANDRES MARCELINO'],
            ['id'=>102,'nombre'=>'DEL ANGEL VIDAL PABLO'],
            ['id'=>103,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>104,'nombre'=>'GARCIA GALINDO ARTURO IZNARD'],
            ['id'=>105,'nombre'=>'HERNANDEZ ROLDAN ISRAEL'],
            ['id'=>106,'nombre'=>'MONTES HERRERA CINTHYA VERONICA'],
            ['id'=>107,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>108,'nombre'=>'TELLEZ ORTEGA EDUARDO ANTONIO'],
            ['id'=>109,'nombre'=>'CABRERA NIETO ERIK'],
            ['id'=>110,'nombre'=>'CUEVAS PALACIOS ESTELA GUADALUPE'],
            ['id'=>111,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>112,'nombre'=>'MADRIGAL VALDEZ LUTGARDA'],
            ['id'=>113,'nombre'=>'MENDOZA FILIDOR ENRIQUE ALBERTO'],
            ['id'=>114,'nombre'=>'POBLETE CRUZ UBALDO'],
            ['id'=>115,'nombre'=>'SILVA FERRUSCA ADRIANA'],
            ['id'=>116,'nombre'=>'VARGAS ALCUDIA JOEL'],
            ['id'=>117,'nombre'=>'DIAZ ALARCON ANGEL DOMINGO'],
            ['id'=>118,'nombre'=>'GARCIA DIAZ JUAN JOSE'],
            ['id'=>119,'nombre'=>'ORTIZ GAMINO HECTOR'],
            ['id'=>120,'nombre'=>'PEREZ CASTRO NANCY'],
            ['id'=>121,'nombre'=>'REYES SIERRA MARIA MARGARITA'],
            ['id'=>122,'nombre'=>'TOVAR SANCHEZ GABRIELA'],
            ['id'=>123,'nombre'=>'ZACARIAS HERNANDEZ VALENTE'],
            ['id'=>124,'nombre'=>'BORJA CASTAÑEDA ESTHER'],
            ['id'=>125,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>126,'nombre'=>'MORENO REYES ARTURO'],
            ['id'=>127,'nombre'=>'REYES SIERRA MARIA MARGARITA'],
            ['id'=>128,'nombre'=>'RODRIGUEZ FERNANDEZ BENITO'],
            ['id'=>129,'nombre'=>'RODRIGUEZ LAGUNES NALDY PATRICIA'],
            ['id'=>130,'nombre'=>'RUIZ ESCOBAR GERADD'],
            ['id'=>131,'nombre'=>'BORJA CASTAÑEDA ESTHER'],
            ['id'=>132,'nombre'=>'CRUZ CASTRO CHRISTIAN'],
            ['id'=>133,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>134,'nombre'=>'GUTIERREZ AGUILAR RAMON ALBERTO'],
            ['id'=>135,'nombre'=>'LASCURAIN FERNANDEZ MAURICIO'],
            ['id'=>136,'nombre'=>'ORTIZ GARCIA JUAN MANUEL'],
            ['id'=>137,'nombre'=>'PORRAS ZARATE ANA LUISA'],
            ['id'=>138,'nombre'=>'SARUR ZANATTA MARIA SUSANA'],
            ['id'=>139,'nombre'=>'SUAREZ SANTOS LILIANA'],
            ['id'=>140,'nombre'=>'ALVAREZ GUILLEN ANTONIO DE JESUS'],
            ['id'=>141,'nombre'=>'ANDRADE AGUILAR ARIADNA'],
            ['id'=>142,'nombre'=>'CARMONA SANCHEZ HECTOR ORLANDO'],
            ['id'=>143,'nombre'=>'CONTRERAS PEREZ RAFAEL MIGUEL'],
            ['id'=>144,'nombre'=>'CUETO ESCOBEDO JONATHAN'],
            ['id'=>145,'nombre'=>'HERNANDEZ ALVAREZ ADRIANA'],
            ['id'=>146,'nombre'=>'SOL RODRIGUEZ MANUEL'],
            ['id'=>147,'nombre'=>'AGUILAR ALEGRE IVAN CARLOS'],
            ['id'=>148,'nombre'=>'DIAZ REBOLLEDO JOSE DE JESUS'],
            ['id'=>149,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>150,'nombre'=>'HERNANDEZ CABRERA OSCAR JESUS'],
            ['id'=>151,'nombre'=>'HERNANDEZ ROBLES JUAN SALVADOR'],
            ['id'=>152,'nombre'=>'LUNA MARTINEZ MARIBEL'],
            ['id'=>153,'nombre'=>'MARTINEZ ESPINOSA JUANA'],
            ['id'=>154,'nombre'=>'RODRIGUEZ RODRIGUEZ JUAN OMAR'],
            ['id'=>155,'nombre'=>'VARGAS ALCUDIA JOEL'],
            ['id'=>156,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>157,'nombre'=>'GARCIA CANO JOSE RAYMUNDO'],
            ['id'=>158,'nombre'=>'LASCURAIN FERNANDEZ MAURICIO'],
            ['id'=>159,'nombre'=>'LOPEZ ROSAS MARIA ANTONIETA'],
            ['id'=>160,'nombre'=>'MORENO REYES ARTURO'],
            ['id'=>161,'nombre'=>'RAMIREZ AYALA GEORGINA MARIA'],
            ['id'=>162,'nombre'=>'RODRIGUEZ FERNANDEZ BENITO'],
            ['id'=>163,'nombre'=>'SANABIA FLORES MARIO'],
            ['id'=>164,'nombre'=>'SUAREZ SANTOS LILIANA'],
            ['id'=>165,'nombre'=>'BARCLAY ARCE EDUARDO'],
            ['id'=>166,'nombre'=>'DIAZ USCANGA JOSE AMADO'],
            ['id'=>167,'nombre'=>'JIMENEZ ALEJO DAVID'],
            ['id'=>168,'nombre'=>'MARINERO URIBE MARIA GUADALUPE'],
            ['id'=>169,'nombre'=>'MENDEZ RODRIGUEZ MARIBEL'],
            ['id'=>170,'nombre'=>'RUIZ ESCOBAR GERADD'],
            ['id'=>171,'nombre'=>'SARUR ZANATTA MARIA SUSANA'],
            ['id'=>172,'nombre'=>'BARCLAY ARCE EDUARDO'],
            ['id'=>173,'nombre'=>'CONTRERAS SANCHEZ IRWING'],
            ['id'=>174,'nombre'=>'GÜIRIS VAZQUEZ AGUSTIN'],
            ['id'=>175,'nombre'=>'HERNANDEZ ROLDAN ISRAEL'],
            ['id'=>176,'nombre'=>'MEDRANO BARRENA JUAN CARLOS'],
            ['id'=>177,'nombre'=>'MONTES HERRERA CINTHYA VERONICA'],
            ['id'=>178,'nombre'=>'TELLEZ ORTEGA EDUARDO ANTONIO'],
            ['id'=>179,'nombre'=>'VERA GUERRA MARIO HUGO'],
            ['id'=>180,'nombre'=>'BELTRAN HERNANDEZ ADRIAN'],
            ['id'=>181,'nombre'=>'CASTILLO MORALES BLANCA ESTELA LIBRADA'],
            ['id'=>182,'nombre'=>'CUEVAS PALACIOS ESTELA GUADALUPE'],
            ['id'=>183,'nombre'=>'DIAZ REBOLLEDO JOSE DE JESUS'],
            ['id'=>184,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>185,'nombre'=>'HERNANDEZ CABRERA OSCAR JESUS'],
            ['id'=>186,'nombre'=>'LUNA PEREZ JONATHAN ALBERTO'],
            ['id'=>187,'nombre'=>'MADRIGAL VALDEZ LUTGARDA'],
            ['id'=>188,'nombre'=>'DIAZ ALARCON ANGEL DOMINGO'],
            ['id'=>189,'nombre'=>'DURAN OLVERA JESSY MARLENE'],
            ['id'=>190,'nombre'=>'ORTIZ GAMINO HECTOR'],
            ['id'=>191,'nombre'=>'PEREA GONZALEZ ROSALIA'],
            ['id'=>192,'nombre'=>'PEREZ CASTRO NANCY'],
            ['id'=>193,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>194,'nombre'=>'ZACARIAS HERNANDEZ VALENTE'],
            ['id'=>195,'nombre'=>'CORRALES AMEZCUA ANDRES MARCELINO'],
            ['id'=>196,'nombre'=>'CRUZ CASTRO CHRISTIAN'],
            ['id'=>197,'nombre'=>'GUTIERREZ AGUILAR RAMON ALBERTO'],
            ['id'=>198,'nombre'=>'LOPEZ ROSAS MARIA ANTONIETA'],
            ['id'=>199,'nombre'=>'MOCTEZUMA PEREZ JOSE ANGEL'],
            ['id'=>200,'nombre'=>'PRADO CABRERA CARLOS GUSTAVO'],
            ['id'=>201,'nombre'=>'RODRIGUEZ LAGUNES NALDY PATRICIA'],
            ['id'=>202,'nombre'=>'ESCOBAR CADENA JOSE ANTONIO'],
            ['id'=>203,'nombre'=>'GALAN PAZARAN CESAR ALEJANDRO'],
            ['id'=>204,'nombre'=>'GUTIERREZ AGUILAR RAMON ALBERTO'],
            ['id'=>205,'nombre'=>'MENDEZ RODRIGUEZ MARIBEL'],
            ['id'=>206,'nombre'=>'ORTIZ GARCIA JUAN MANUEL'],
            ['id'=>207,'nombre'=>'PEREZ LOPEZ JULIETA'],
            ['id'=>208,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>209,'nombre'=>'SIFUENTES GARCIA MIRIAM DEL CARMEN'],
            ['id'=>210,'nombre'=>'ANDRADE AGUILAR ARIADNA'],
            ['id'=>211,'nombre'=>'CONTRERAS PEREZ RAFAEL MIGUEL'],
            ['id'=>212,'nombre'=>'CUETO ESCOBEDO JONATHAN'],
            ['id'=>213,'nombre'=>'KAI CACHO VICTORIA'],
            ['id'=>214,'nombre'=>'SOL RODRIGUEZ MANUEL'],
            ['id'=>215,'nombre'=>'TORRES MORALES PATRICIA'],
            ['id'=>216,'nombre'=>'UTRERA HERNANDEZ MARIBEL'],
            ['id'=>217,'nombre'=>'BARCLAY ARCE EDUARDO'],
            ['id'=>218,'nombre'=>'CRUZ CASTRO CHRISTIAN'],
            ['id'=>219,'nombre'=>'ELORZA VASQUEZ MIGUEL ANGEL'],
            ['id'=>220,'nombre'=>'FERNANDEZ RIVERA ADAENA'],
            ['id'=>221,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>222,'nombre'=>'GÜIRIS VAZQUEZ AGUSTIN'],
            ['id'=>223,'nombre'=>'MEDRANO BARRENA JUAN CARLOS'],
            ['id'=>224,'nombre'=>'TELLEZ ORTEGA EDUARDO ANTONIO'],
            ['id'=>225,'nombre'=>'AZUARA SANCHEZ RODOLFO'],
            ['id'=>226,'nombre'=>'BELTRAN HERNANDEZ ADRIAN'],
            ['id'=>227,'nombre'=>'CAMACHO ACOSTA FRANCISCO JAVIER'],
            ['id'=>228,'nombre'=>'CASTILLO MORALES BLANCA ESTELA LIBRADA'],
            ['id'=>229,'nombre'=>'CHIPULI CASTILLO ARTURO MIGUEL'],
            ['id'=>230,'nombre'=>'GARCIA GONZALEZ JESUS OCTAVIO'],
            ['id'=>231,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>232,'nombre'=>'MARTINEZ ESPINOSA JUANA'],
            ['id'=>233,'nombre'=>'BARCLAY ARCE EDUARDO'],
            ['id'=>234,'nombre'=>'CASTILLO MARTINEZ SAHAMALIA CRISTINA'],
            ['id'=>235,'nombre'=>'DIAZ ROMERO JOSE AGUSTIN'],
            ['id'=>236,'nombre'=>'GALICIA MONTES GLORIA'],
            ['id'=>237,'nombre'=>'MARINERO URIBE MARIA GUADALUPE'],
            ['id'=>238,'nombre'=>'MOCTEZUMA PEREZ JOSE ANGEL'],
            ['id'=>239,'nombre'=>'PRADO CABRERA CARLOS GUSTAVO'],
            ['id'=>240,'nombre'=>'DEL ANGEL VIDAL PABLO'],
            ['id'=>241,'nombre'=>'ELORZA VASQUEZ MIGUEL ANGEL'],
            ['id'=>242,'nombre'=>'GARCIA GALINDO ARTURO IZNARD'],
            ['id'=>243,'nombre'=>'GARCIA LANDERO JULIO CESAR'],
            ['id'=>244,'nombre'=>'GONZALEZ ARROYO FERNANDO AXAYACATL'],
            ['id'=>245,'nombre'=>'GÜIRIS VAZQUEZ AGUSTIN'],
            ['id'=>246,'nombre'=>'ANIEVA LADRON DE GUEVARA LETICIA'],
            ['id'=>247,'nombre'=>'CAMACHO ACOSTA FRANCISCO JAVIER'],
            ['id'=>248,'nombre'=>'CARILLO CUEVAS PEDRO CARLOS'],
            ['id'=>249,'nombre'=>'GARCIA HERRERA BENJAMIN'],
            ['id'=>250,'nombre'=>'GARCIA HERRERA CARLOS M'],
            ['id'=>251,'nombre'=>'HERNANDEZ CABRERA OSCAR JESUS'],
            ['id'=>252,'nombre'=>'MORALES CORTES BALDEMAR'],
            ['id'=>253,'nombre'=>'LUNA PEREZ JONATHAN ALBERTO'],
            ['id'=>254,'nombre'=>'PEDREGUERA GARCIA CARLOS ALBERTO'],
            ['id'=>255,'nombre'=>'DIAZ ALARCON ANGEL DOMINGO'],
            ['id'=>256,'nombre'=>'GALAN PAZARAN CESAR ALEJANDRO'],
            ['id'=>257,'nombre'=>'GARCIA DIAZ JUAN JOSE'],
            ['id'=>258,'nombre'=>'RIOS GABRIEL ESLYSS'],
            ['id'=>259,'nombre'=>'SANDRIA FLORES DANIEL'],
            ['id'=>260,'nombre'=>'SARUR ZANATTA MARIA SUSANA'],
            ['id'=>261,'nombre'=>'BORJA CASTAÑEDA ESTHER'],
            ['id'=>262,'nombre'=>'CRUZ CASTRO CHRISTIAN'],
            ['id'=>263,'nombre'=>'FLORES RUIZ LEONEL EDUARDO'],
            ['id'=>264,'nombre'=>'GARCIA CANO JOSE RAYMUNDO'],
            ['id'=>265,'nombre'=>'LOPEZ ROSAS MARIA ANTONIETA'],
            ['id'=>266,'nombre'=>'MOCTEZUMA PEREZ JOSE ANGEL'],
            ['id'=>267,'nombre'=>'PADILLA VASQUEZ DAYANA JOVANA'],
            ['id'=>268,'nombre'=>'BORJA CASTAÑEDA ESTHER'],
            ['id'=>269,'nombre'=>'GALAN PAZARAN CESAR ALEJANDRO'],
            ['id'=>270,'nombre'=>'GARCIA GALINDO ARTURO IZNARD'],
            ['id'=>271,'nombre'=>'PRETELIN MUÑOZ ARMINDA CONCEPCION'],
            ['id'=>272,'nombre'=>'RAMIREZ AYALA GEORGINA MARIA'],
            ['id'=>273,'nombre'=>'SERENA BENITEZ CITLALLI'],
            ['id'=>274,'nombre'=>'SIFUENTES GARCIA MIRIAM DEL CARMEN'],
            ['id'=>275,'nombre'=>'ZARATE MEJIA ESTEBAN JUAN BAUTISTA'],
            ['id'=>276,'nombre'=>'ALVAREZ GUILLEN ANTONIO DE JESUS'],
            ['id'=>277,'nombre'=>'CARMONA SANCHEZ HECTOR ORLANDO'],
            ['id'=>278,'nombre'=>'HERNANDEZ ALVAREZ ADRIANA'],
            ['id'=>279,'nombre'=>'ROSAS SANTIAGO FRANCISCO JAVIER'],
            ['id'=>280,'nombre'=>'TELLO BELLO MARIA AMANDA JULIETA'],
            ['id'=>281,'nombre'=>'YEPEZ OLVERA LILIANA'],
            ['id'=>282,'nombre'=>'GOMEZ MILLAN VALERIA'],
            ['id'=>283,'nombre'=>'HERNANDEZ ROBLES JUAN SALVADOR'],
            ['id'=>284,'nombre'=>'HERNANDEZ ROBLES JUAN SALVADOR'],
            ['id'=>285,'nombre'=>'MENDOZA ANDONEGUI HEBER'],
            ['id'=>286,'nombre'=>'PEREZ LOPEZ JULIETA'],
            ['id'=>287,'nombre'=>'ROJAS CABRERA CRISTABEL'],
            ['id'=>288,'nombre'=>'HERNANDEZ ROBLES JUAN SALVADOR'],
            ['id'=>289,'nombre'=>'MENDOZA ANDONEGUI HEBER'],
            ['id'=>290,'nombre'=>'GOMEZ MILLAN VALERIA'],
            ['id'=>291,'nombre'=>'MENDOZA ANDONEGUI HEBER'],
            ['id'=>292,'nombre'=>'ROJAS CABRERA CRISTABEL'],
            ['id'=>293,'nombre'=>'ROJAS CABRERA CRISTABEL'],
            ['id'=>294,'nombre'=>'ROJAS CABRERA CRISTABEL'],
            ['id'=>295,'nombre'=>'SANABIA FLORES MARIO'],
            ['id'=>296,'nombre'=>'HERNANDEZ ROBLES JUAN SALVADOR'],

           
        ]);
    }
}
